### ISSUE TITLE
Lots of 404 for assets

### ISSUE THREAD

**Issue by danieldanielecki** [grzesiekmq/supercars-dream#3]
This projects returns many `404` errors for loading assets, which causes to have the game to display as the screenshot below shows. As well as it's infeasible to play it (see anything playable).

<img width="1303" alt="404" src="https://user-images.githubusercontent.com/12736263/77247537-71b3e100-6c32-11ea-8530-a6a415740f0d.png">

**Comment by grzesiekmq** [comment]
yes because not included in project repo thx

**Comment by danieldanielecki** [comment]
@grzesiekmq what's the point then making this repository public?
