### ISSUE TITLE
Module not found: Error: Can't resolve './components/TestDrive.vue'

### ISSUE THREAD

**Issue by danieldanielecki** [grzesiekmq/supercars-dream#4]
The `TestDrive.vue` component is apparently missing and `webpack` won't compile this unless the file won't be commented out. I guess it's a missing file.

**Comment by grzesiekmq** [comment]
thank you for feedback I'm back to this project :)
but probably abandon vue because I have issues with babylon.js + vue
and considering playcanvas instead of babylonjs
yes the TestDrive.vue is missing because I forgot to add to git

**Comment by danieldanielecki** [comment]
@grzesiekmq would you be able to upload the `TestDrive.vue` file?
